# Generated by Django 6.0.3 on 2026-03-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_product_sale_delete_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
